/* Carestep Home PWA v10.1-B · Journey and preventive care Web Push */
(() => {
  'use strict';
  const API='https://carestep-ai-api.kk04sdw.workers.dev';
  const SESSION_KEY='carestep_home_session_v1';
  const $=id=>document.getElementById(id);
  const TYPE_META={weight:{label:'체중',icon:'kg'},vaccination:{label:'접종',icon:'V'},heartworm:{label:'사상충',icon:'H'},visit:{label:'진료',icon:'+'},journey:{label:'Journey',icon:'J'},appetite:{label:'식욕',icon:'A'},water:{label:'음수',icon:'W'},vomiting:{label:'구토',icon:'V'},diarrhea:{label:'설사',icon:'D'},medication:{label:'투약',icon:'M'}};
  const LEVEL_OPTIONS={appetite:[['good','좋음'],['normal','보통'],['reduced','감소'],['none','거의 먹지 않음']],water:[['','선택 안 함'],['less','평소보다 적음'],['normal','평소와 비슷'],['more','평소보다 많음']]};
  const query=new URLSearchParams(location.search);
  const state={token:localStorage.getItem(SESSION_KEY)||'',inviteToken:query.get('invite')||'',deepLinkFollowupId:query.get('followup')||'',deepLinkPatientId:query.get('patient')||'',deepLinkEventId:query.get('event')||'',installPrompt:null,registration:null,home:null,active:null,timeline:null,filter:'all',editing:null,followups:[],followupSummary:{today:0,overdue:0,upcoming:0,completed:0},followupFilter:'today',followupLoading:false,followupError:'',pushBusy:false,pushSubscription:null};
  const views=['loadingView','inviteView','loginView','dashboardView','patientView','errorView'];
  const esc=v=>String(v??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
  const speciesLabel=v=>({dog:'강아지',cat:'고양이',other:'반려동물'})[v]||'반려동물';
  const sexLabel=v=>({male:'수컷',female:'암컷',unknown:'성별 미확인'})[v]||'성별 미확인';
  const sourceLabel=v=>v==='home'?'보호자 기록':v==='system'?'병원 자동 기록':'병원 기록';
  const dateLabel=v=>{if(!v)return '미입력';const d=new Date(v+'T00:00:00');return Number.isNaN(d.getTime())?v:d.toLocaleDateString('ko-KR',{year:'numeric',month:'short',day:'numeric'});};
  function show(id){for(const key of views){const el=$(key);if(el)el.hidden=key!==id;}window.scrollTo({top:0,behavior:'smooth'});}
  function status(id,text='',kind=''){const el=$(id);if(!el)return;el.textContent=text;el.className='home-status '+kind;}
  async function api(path,opt={}){const headers={'Content-Type':'application/json',...(opt.headers||{})};if(opt.auth!==false&&state.token)headers.Authorization='Bearer '+state.token;let response;try{response=await fetch(API+path,{...opt,headers,cache:'no-store'});}catch{throw new Error(navigator.onLine?'서버에 연결하지 못했습니다. 잠시 후 다시 시도해주세요.':'인터넷 연결을 확인해주세요.');}let data={};try{data=await response.json();}catch{}if(!response.ok)throw Object.assign(new Error(data.error||'요청을 처리하지 못했습니다.'),{status:response.status});return data;}
  function patientHtml(p){return `<div class="invite-pet"><span class="pet-avatar ${p.species==='cat'?'cat':''}">${p.species==='cat'?'CAT':'PET'}</span><span><b>${esc(p.name||'이름 미입력')}</b><span>${esc([speciesLabel(p.species),p.breed].filter(Boolean).join(' · '))}</span></span></div>`;}
  async function loadInvite(){show('loadingView');try{const data=await api('/home/invite/'+encodeURIComponent(state.inviteToken),{method:'GET',auth:false});const invite=data.invite;$('inviteGuardianName').textContent=invite.guardianName||'보호자';$('inviteLead').textContent=`${invite.clinicName}에서 ${(invite.patients||[]).length}마리의 연결을 보냈습니다.`;$('inviteClinic').textContent='🏥 '+invite.clinicName;$('invitePatients').innerHTML=(invite.patients||[]).map(patientHtml).join('');$('invitePhoneHint').textContent=`${invite.phoneHint}로 표시되는 병원 등록 번호의 끝 4자리를 입력해주세요.`;show('inviteView');}catch(e){showError(e.message);}}
  async function acceptInvite(event){event.preventDefault();status('inviteStatus');const button=$('inviteSubmit');button.disabled=true;button.textContent='안전하게 연결하는 중…';try{const data=await api('/home/invite/'+encodeURIComponent(state.inviteToken),{method:'POST',auth:false,body:JSON.stringify({phoneLast4:$('inviteLast4').value,password:$('invitePassword').value,termsAccepted:$('inviteTerms').checked,privacyAccepted:$('invitePrivacy').checked})});state.token=data.session.token;localStorage.setItem(SESSION_KEY,state.token);history.replaceState({},'',location.pathname);renderHome(data.home);show('dashboardView');}catch(e){status('inviteStatus',e.message,'error');}finally{button.disabled=false;button.textContent='계정 만들고 환자 연결';}}
  async function login(event){event.preventDefault();status('loginStatus');const button=$('loginSubmit');button.disabled=true;button.textContent='로그인 중…';try{const data=await api('/home/login',{method:'POST',auth:false,body:JSON.stringify({phone:$('loginPhone').value,password:$('loginPassword').value})});state.token=data.session.token;localStorage.setItem(SESSION_KEY,state.token);renderHome(data.home);show('dashboardView');await openPreventiveDeepLink();}catch(e){status('loginStatus',e.message,'error');}finally{button.disabled=false;button.textContent='로그인';}}
  function connectionHtml(c,locked){return `<article class="connection-clinic"><div class="connection-clinic-head"><div><span>연결 병원</span><b>${esc(c.clinicName)}</b></div><small>연결됨</small></div><div class="connection-pets">${(c.patients||[]).map(p=>`<button class="connection-pet" type="button" data-home-patient="${esc(p.id)}" ${locked?'disabled':''}><span class="pet-avatar ${p.species==='cat'?'cat':''}">${p.species==='cat'?'CAT':'PET'}</span><span><b>${esc(p.name)}</b><small>${esc([speciesLabel(p.species),p.breed,sexLabel(p.sex)].filter(Boolean).join(' · '))}</small><em>${locked?'동의 후 확인':'건강 기록 보기 →'}</em></span></button>`).join('')}</div></article>`;}
  function renderHome(home){state.home=home;$('homeUserName').textContent=home?.user?.displayName||'보호자';const locked=!!home?.consentRequired,connections=home?.connections||[];$('homeHealthConsent').hidden=!locked;$('homeFollowupSection').hidden=locked;$('homePushCard').hidden=locked;$('homeConnections').innerHTML=connections.length?connections.map(c=>connectionHtml(c,locked)).join(''):'<div class="stage-note"><b>연결된 환자가 없습니다</b><p>병원에 환자 연결 상태를 확인해주세요.</p></div>';$('homeConnections').querySelectorAll('[data-home-patient]').forEach(button=>button.addEventListener('click',()=>openPatient(button.dataset.homePatient)));if(!locked){loadFollowups();refreshPushStatus();}}
  const pushSupported=()=>('serviceWorker' in navigator)&&('PushManager' in window)&&('Notification' in window);
  const isIos=()=>/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);
  const isStandalone=()=>window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true;
  function pushApplicationKey(value){let s=String(value||'').replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const raw=atob(s),out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out;}
  function pushUi(kind,message=''){
    const card=$('homePushCard'),badge=$('homePushBadge'),button=$('homePushToggle'),test=$('homePushTest');if(!card)return;card.classList.toggle('unsupported',kind==='unsupported');badge.className=kind==='active'?'active':kind==='blocked'||kind==='unsupported'?'blocked':'';badge.textContent={active:'켜짐',inactive:'꺼짐',blocked:'권한 차단',unsupported:'지원 안 됨',unavailable:'서버 준비 중',loading:'확인 중'}[kind]||'확인 중';button.disabled=state.pushBusy||['blocked','unsupported','unavailable','loading'].includes(kind);button.textContent=kind==='active'?'알림 끄기':'알림 켜기';test.hidden=kind!=='active';if(message)$('homePushMessage').textContent=message;
  }
  async function pushRegistration(){if(state.registration)return state.registration;if(!pushSupported())return null;state.registration=await navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'});return state.registration}
  async function refreshPushStatus(){
    if(!state.token||state.home?.consentRequired)return;$('homePushCard').hidden=false;status('homePushStatus');if(!pushSupported()){const iosHint=isIos()&&!isStandalone()?'iPhone에서는 Safari 공유 버튼의 “홈 화면에 추가”로 앱을 설치한 뒤 알림을 켤 수 있습니다.':'이 브라우저에서는 앱 푸시 알림을 지원하지 않습니다.';pushUi('unsupported',iosHint);return}
    if(Notification.permission==='denied'){pushUi('blocked','브라우저 설정에서 Carestep Home 알림 권한을 허용해주세요.');return}pushUi('loading');try{const [server,registration]=await Promise.all([api('/home/push',{method:'GET'}),pushRegistration()]);if(!server.enabled){pushUi('unavailable','앱 푸시 서버 설정이 아직 완료되지 않았습니다.');return}state.pushSubscription=await registration.pushManager.getSubscription();if(state.pushSubscription&&Notification.permission==='granted'){const payload=state.pushSubscription.toJSON();await api('/home/push/subscriptions',{method:'POST',body:JSON.stringify({...payload,userAgent:navigator.userAgent})});pushUi('active','Journey 관리와 접종·심장사상충 예정일을 휴대전화 알림으로 알려드려요.');}else pushUi('inactive','Journey 관리와 접종·심장사상충 예정일을 휴대전화 알림으로 알려드려요.');}catch(e){pushUi('unavailable','알림 연결 상태를 확인하지 못했습니다.');status('homePushStatus',e.message,'error');}
  }
  async function togglePush(){
    if(state.pushBusy||!pushSupported())return;state.pushBusy=true;status('homePushStatus');try{const registration=await pushRegistration(),current=await registration.pushManager.getSubscription();if(current){const endpoint=current.endpoint;await api('/home/push/subscriptions',{method:'DELETE',body:JSON.stringify({endpoint})});await current.unsubscribe();state.pushSubscription=null;status('homePushStatus','이 기기의 앱 알림을 껐습니다.','ok');}else{if(isIos()&&!isStandalone())throw new Error('iPhone에서는 먼저 Carestep Home을 홈 화면에 추가한 뒤 설치된 앱에서 알림을 켜주세요.');const server=await api('/home/push',{method:'GET'});if(!server.enabled||!server.publicKey)throw new Error('앱 푸시 서버 설정이 아직 완료되지 않았습니다.');const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('알림 권한이 허용되지 않았습니다. 브라우저 설정에서 권한을 확인해주세요.');const subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:pushApplicationKey(server.publicKey)}),payload=subscription.toJSON();await api('/home/push/subscriptions',{method:'POST',body:JSON.stringify({...payload,userAgent:navigator.userAgent})});state.pushSubscription=subscription;status('homePushStatus','알림이 켜졌습니다. 시험 알림으로 확인할 수 있습니다.','ok');}}catch(e){status('homePushStatus',e.message,'error');}finally{state.pushBusy=false;await refreshPushStatus();}
  }
  async function testPush(){const button=$('homePushTest');button.disabled=true;button.textContent='전송 중…';status('homePushStatus');try{const data=await api('/home/push/test',{method:'POST'});status('homePushStatus',`시험 알림을 ${Number(data.sent)||1}대 기기로 보냈습니다.`,'ok');}catch(e){status('homePushStatus',e.message,'error');}finally{button.disabled=false;button.textContent='시험 알림';}}
  function openDeepLinkedFollowup(){const id=state.deepLinkFollowupId;if(!id)return;state.followupFilter='all';renderFollowups();requestAnimationFrame(()=>{const details=$('homeFollowupList')?.querySelector(`[data-followup-details="${CSS.escape(id)}"]`);if(!details)return;details.open=true;details.closest('.home-followup-card')?.scrollIntoView({behavior:'smooth',block:'center'});state.deepLinkFollowupId='';const url=new URL(location.href);url.searchParams.delete('followup');history.replaceState({},'',url.pathname+url.search);});}
  async function openPreventiveDeepLink(){const id=state.deepLinkPatientId;if(!id||!patientContext(id))return;await openPatient(id);}
  function focusDeepLinkedEvent(){const id=state.deepLinkEventId;if(!id)return;requestAnimationFrame(()=>{const card=$('patientTimelineList')?.querySelector(`[data-home-event="${CSS.escape(id)}"]`);if(!card)return;card.classList.add('deep-linked');card.scrollIntoView({behavior:'smooth',block:'center'});state.deepLinkPatientId='';state.deepLinkEventId='';const url=new URL(location.href);url.searchParams.delete('patient');url.searchParams.delete('event');history.replaceState({},'',url.pathname+url.search);});}
  const FOLLOWUP_RESPONSE_LABEL={good:'괜찮아요',watch:'관찰이 필요해요',concern:'병원 상담이 필요해요'};
  function followupDateState(item){if(item.status==='completed')return 'completed';if(item.dueDate<today())return 'overdue';if(item.dueDate===today())return 'today';return 'upcoming';}
  function followupStatusLabel(item){const kind=followupDateState(item);if(kind==='completed')return '응답 완료';if(kind==='overdue')return '확인 필요';if(kind==='today')return '오늘';return '예정';}
  function followupMobileCardHtml(item){const card=item.card||{},checks=Array.isArray(card.checks)?card.checks:[],reds=Array.isArray(card.redFlags)?card.redFlags:[],hasCard=card.focus||checks.length||reds.length;if(!hasCard)return `<p>${esc(item.message)}</p>`;return `<section class="home-mobile-care-card"><header><div><span>CARESTEP · ${esc(item.clinicName)}</span><b>D+${Number(item.stageDay)||0}</b></div><small>${dateLabel(item.dueDate)} · ${esc(item.patientName)}</small><h3>${esc(item.title)}</h3><p>${esc(card.journey||'Journey 후속관리')} · 오늘 보호자가 확인할 핵심 항목입니다.</p></header>${card.focus?`<div class="home-mobile-focus"><b>TODAY'S FOCUS</b><span>${esc(card.focus)}</span></div>`:''}${checks.length?`<div class="home-mobile-checks">${checks.map(x=>`<div><i></i><span>${esc(x)}</span></div>`).join('')}</div>`:''}${reds.length?`<div class="home-mobile-red"><b>이런 변화는 기다리지 말고 연락하세요</b><p>${reds.map(esc).join(' · ')}</p></div>`:''}${card.recheck?`<div class="home-mobile-recheck"><b>다음 재진</b><span>${esc(card.recheck)}</span></div>`:''}<footer><b>${esc(item.clinicName)}</b><span>${esc(card.hospitalPhone||'병원 대표전화로 문의')}</span></footer></section>`;}
  function followupCardHtml(item){const kind=followupDateState(item),canRespond=kind!=='upcoming'&&kind!=='completed',response=item.responseCode?`<div class="home-followup-response saved"><b>${esc(FOLLOWUP_RESPONSE_LABEL[item.responseCode]||'확인 완료')}</b>${item.responseNote?`<p>${esc(item.responseNote)}</p>`:''}<small>${item.completedAt?new Date(item.completedAt).toLocaleString('ko-KR'):'응답 완료'}</small></div>`:'',form=canRespond?`<form class="home-followup-response" data-followup-response="${esc(item.id)}"><fieldset><legend>현재 상태를 알려주세요</legend><label><input type="radio" name="followup-${esc(item.id)}" value="good" required><span>괜찮아요</span></label><label><input type="radio" name="followup-${esc(item.id)}" value="watch"><span>관찰이 필요해요</span></label><label class="concern"><input type="radio" name="followup-${esc(item.id)}" value="concern"><span>병원 상담이 필요해요</span></label></fieldset><textarea maxlength="500" placeholder="병원에 함께 전달할 메모가 있다면 적어주세요. (선택)"></textarea><div class="home-followup-response-status" role="status"></div><button class="home-primary" type="submit">확인 완료</button></form>`:kind==='upcoming'?'<div class="home-followup-future">예정일이 되면 현재 상태를 응답할 수 있습니다.</div>':'';return `<article class="home-followup-card ${kind}"><details data-followup-details="${esc(item.id)}"><summary><div class="home-followup-day">D+${Number(item.stageDay)||0}</div><div class="home-followup-summary"><span>${esc(item.patientName)} · ${esc(item.clinicName)}</span><b>${esc(item.title)}</b><small>${dateLabel(item.dueDate)}</small></div><em>${followupStatusLabel(item)}</em></summary><div class="home-followup-content">${followupMobileCardHtml(item)}${response||form}</div></details></article>`;}
  function renderFollowups(){const section=$('homeFollowupSection');if(!section||section.hidden)return;const s=state.followupSummary||{};$('homeFollowupToday').textContent=String(s.today||0);$('homeFollowupOverdue').textContent=String(s.overdue||0);$('homeFollowupUpcoming').textContent=String(s.upcoming||0);$('homeFollowupCompleted').textContent=String(s.completed||0);const filters=[['today','오늘·확인 필요'],['upcoming','예정'],['completed','완료'],['all','전체']];$('homeFollowupFilters').innerHTML=filters.map(([k,v])=>`<button class="${state.followupFilter===k?'active':''}" type="button" data-followup-filter="${k}">${v}</button>`).join('');$('homeFollowupFilters').querySelectorAll('[data-followup-filter]').forEach(button=>button.addEventListener('click',()=>{state.followupFilter=button.dataset.followupFilter;renderFollowups();}));let rows=state.followups||[];if(state.followupFilter==='today')rows=rows.filter(x=>['today','overdue'].includes(followupDateState(x)));else if(state.followupFilter!=='all')rows=rows.filter(x=>followupDateState(x)===state.followupFilter);$('homeFollowupList').innerHTML=state.followupLoading?'<div class="home-followup-empty"><span class="home-spinner"></span><b>후속관리를 불러오는 중입니다</b></div>':state.followupError?`<div class="home-followup-empty"><b>후속관리를 불러오지 못했습니다</b><p>${esc(state.followupError)}</p></div>`:rows.length?rows.map(followupCardHtml).join(''):'<div class="home-followup-empty"><b>표시할 후속관리가 없습니다</b><p>병원에서 Journey 후속관리를 보내면 이곳에 표시됩니다.</p></div>';$('homeFollowupList').querySelectorAll('[data-followup-details]').forEach(details=>details.addEventListener('toggle',()=>{if(details.open)markFollowupRead(details.dataset.followupDetails,details);}));$('homeFollowupList').querySelectorAll('[data-followup-response]').forEach(form=>form.addEventListener('submit',submitFollowupResponse));}
  async function loadFollowups(){if(!state.token||state.home?.consentRequired)return;state.followupLoading=true;state.followupError='';renderFollowups();try{const data=await api('/home/followups?limit=200',{method:'GET'});state.followups=data.items||[];state.followupSummary=data.summary||{};}catch(e){state.followups=[];state.followupError=e.message||'잠시 후 다시 시도해주세요.';}finally{state.followupLoading=false;renderFollowups();openDeepLinkedFollowup();}}
  async function markFollowupRead(id,details){const item=state.followups.find(x=>x.id===id);if(!item||item.status!=='scheduled')return;try{await api('/home/followups/'+encodeURIComponent(id)+'/read',{method:'POST'});item.status='seen';const badge=details.querySelector('summary em');if(badge)badge.textContent=followupStatusLabel(item);}catch{}}
  async function submitFollowupResponse(event){event.preventDefault();const form=event.currentTarget,id=form.dataset.followupResponse,selected=form.querySelector('input[type="radio"]:checked'),note=form.querySelector('textarea').value.trim(),button=form.querySelector('button[type="submit"]'),out=form.querySelector('.home-followup-response-status');if(!selected){out.textContent='현재 상태를 선택해주세요.';return;}button.disabled=true;button.textContent='전달 중…';out.textContent='';try{await api('/home/followups/'+encodeURIComponent(id)+'/respond',{method:'POST',body:JSON.stringify({responseCode:selected.value,note})});await loadFollowups();}catch(e){out.textContent=e.message||'응답을 전달하지 못했습니다.';button.disabled=false;button.textContent='확인 완료';}}
  function patientContext(patientId){for(const connection of (state.home?.connections||[])){const patient=(connection.patients||[]).find(p=>p.id===patientId);if(patient)return {patient,connection};}return null;}
  async function acceptHealthConsent(){if(!$('homeHealthConsentCheck').checked){status('homeHealthConsentStatus','건강기록과 후속관리 연결 안내에 동의해주세요.','error');return;}const button=$('homeHealthConsentSubmit');button.disabled=true;try{const data=await api('/home/health-consent',{method:'POST',body:JSON.stringify({privacyAccepted:true})});renderHome(data.home);status('homeHealthConsentStatus','동의가 완료되었습니다. 병원 기록과 후속관리 안내를 확인할 수 있습니다.','ok');}catch(e){status('homeHealthConsentStatus',e.message,'error');}finally{button.disabled=false;}}
  function chartHtml(series){if(!series||series.length<2)return '<div class="home-chart-empty">체중 기록이 2회 이상 쌓이면 변화 그래프가 표시됩니다.</div>';const pts=series.slice(-10),values=pts.map(x=>Number(x.value)),min=Math.min(...values),max=Math.max(...values),range=max-min||1,w=520,h=120,p=20,coords=pts.map((x,i)=>({x:p+i*(w-p*2)/Math.max(1,pts.length-1),y:h-p-(Number(x.value)-min)*(h-p*2)/range,v:Number(x.value),d:x.date}));return `<div class="home-chart"><svg viewBox="0 0 ${w} ${h}" role="img" aria-label="최근 체중 변화"><line x1="${p}" y1="${h-p}" x2="${w-p}" y2="${h-p}"/><polyline points="${coords.map(x=>`${x.x},${x.y}`).join(' ')}"/>${coords.map(x=>`<circle cx="${x.x}" cy="${x.y}" r="4"><title>${esc(x.d)} · ${x.v}kg</title></circle>`).join('')}</svg><div><span>${esc(pts[0].date)}</span><b>${min===max?`${min}kg`:`${min}–${max}kg`}</b><span>${esc(pts.at(-1).date)}</span></div></div>`;}
  function eventHtml(e){const meta=TYPE_META[e.type]||{label:e.type,icon:'·'},value=e.value!==''&&e.value!==null&&e.value!==undefined?`<strong>${esc(e.value)}${esc(e.unit||(e.type==='weight'?'kg':''))}</strong>`:'',due=e.nextDueDate?`<div class="home-event-due"><span>다음 예정</span><b>${dateLabel(e.nextDueDate)}</b></div>`:'',note=e.homeNote?`<p>${esc(e.homeNote)}</p>`:'',journey=e.type==='journey'?`<span class="home-event-status">${e.status==='completed'?'완료':'진행 중'}</span>`:'',actions=e.ownedByMe?`<div class="home-event-actions"><button type="button" data-home-record-edit="${esc(e.id)}">수정</button><button type="button" data-home-record-delete="${esc(e.id)}">삭제</button></div>`:'';return `<article class="home-event ${e.source==='home'?'home-origin':''}" data-home-event="${esc(e.id)}"><div class="home-event-marker type-${esc(e.type)}">${esc(meta.icon)}</div><div class="home-event-body"><div class="home-event-head"><span>${dateLabel(e.eventDate)}</span><span class="home-event-head-right">${journey}${actions}</span></div><div class="home-event-title"><b>${esc(e.title||meta.label)}</b>${value}</div><div class="home-event-meta"><span>${esc(meta.label)}</span><span>${esc(sourceLabel(e.source))}</span></div>${due}${note}</div></article>`;}
  function renderTimeline(){const data=state.timeline;if(!data)return;const rows=state.filter==='all'?data.events:(data.events||[]).filter(e=>e.type===state.filter),next=data.summary?.upcoming;$('patientLatestWeight').textContent=data.summary?.latestWeightKg!==''&&data.summary?.latestWeightKg!=null?`${data.summary.latestWeightKg}kg`:'미입력';$('patientNextDate').textContent=next?dateLabel(next.nextDueDate):'없음';$('patientNextTitle').textContent=next?.title||'예정된 일정 없음';$('patientRecordCount').textContent=`${Number(data.summary?.total)||0}건`;$('patientWeightChart').innerHTML=chartHtml(data.weightSeries||[]);$('patientTimelineFilters').innerHTML=[['all','전체'],...Object.entries(TYPE_META).map(([k,v])=>[k,v.label])].map(([k,v])=>`<button class="${state.filter===k?'active':''}" type="button" data-home-filter="${k}">${esc(v)}</button>`).join('');$('patientTimelineList').innerHTML=rows.length?rows.map(eventHtml).join(''):'<div class="home-timeline-empty"><b>표시할 건강 기록이 없습니다</b><p>병원 공개 기록과 직접 작성한 홈 기록이 이곳에 표시됩니다.</p></div>';$('patientTimelineFilters').querySelectorAll('[data-home-filter]').forEach(button=>button.addEventListener('click',()=>{state.filter=button.dataset.homeFilter;renderTimeline();}));$('patientTimelineList').querySelectorAll('[data-home-record-edit]').forEach(button=>button.addEventListener('click',()=>openHomeRecord((data.events||[]).find(e=>e.id===button.dataset.homeRecordEdit))));$('patientTimelineList').querySelectorAll('[data-home-record-delete]').forEach(button=>button.addEventListener('click',()=>deleteHomeRecord(button.dataset.homeRecordDelete)));focusDeepLinkedEvent();}
  const today=()=>new Date(Date.now()+9*60*60*1000).toISOString().slice(0,10);
  function closeHomeRecord(){const dialog=$('homeRecordDialog');state.editing=null;if(typeof dialog?.close==='function')dialog.close();else dialog?.removeAttribute('open');}
  function recordLevel(type,title=''){const options=LEVEL_OPTIONS[type]||[];return options.find(([,label])=>label&&String(title).includes(label))?.[0]||'';}
  function syncHomeRecordFields(){const type=$('homeRecordType').value,valueField=$('homeRecordValueField'),levelField=$('homeRecordLevelField'),medField=$('homeRecordMedicationField'),value=$('homeRecordValue'),level=$('homeRecordLevel'),medication=$('homeRecordMedication'),label=$('homeRecordValueLabel'),unit=$('homeRecordValueUnit'),options=LEVEL_OPTIONS[type]||[];valueField.hidden=!['weight','water','vomiting','diarrhea'].includes(type);levelField.hidden=!options.length;medField.hidden=type!=='medication';value.required=['weight','vomiting','diarrhea'].includes(type);level.required=type==='appetite';medication.required=type==='medication';level.innerHTML=options.map(([v,t])=>`<option value="${v}">${esc(t)}</option>`).join('');if(type==='weight'){label.textContent='체중';unit.textContent='kg';value.min='0.01';value.max='200';value.step='0.01';value.placeholder='예: 4.8';}if(type==='water'){label.textContent='측정 음수량 (선택)';unit.textContent='ml';value.min='1';value.max='20000';value.step='1';value.placeholder='예: 350';}if(type==='vomiting'||type==='diarrhea'){label.textContent=type==='vomiting'?'구토 횟수':'설사 횟수';unit.textContent='회';value.min='1';value.max='50';value.step='1';value.placeholder='예: 2';}}
  function openHomeRecord(event=null){if(!state.active)return;const allowed=['weight','appetite','water','vomiting','diarrhea','medication'],type=allowed.includes(event?.type)?event.type:'weight';state.editing=event||null;$('homeRecordForm').reset();$('homeRecordId').value=event?.id||'';$('homeRecordDialogTitle').textContent=event?'홈 기록 수정':`${state.active.patient.name||'반려동물'} 홈 기록 추가`;$('homeRecordType').value=type;$('homeRecordDate').max=today();$('homeRecordDate').value=event?.eventDate||today();syncHomeRecordFields();$('homeRecordValue').value=event?.value??'';$('homeRecordLevel').value=recordLevel(type,event?.title||'');$('homeRecordMedication').value=type==='medication'?String(event?.title||'').replace(/^투약\s*·\s*/,''):'';$('homeRecordNote').value=event?.homeNote||'';status('homeRecordStatus');const dialog=$('homeRecordDialog');if(typeof dialog?.showModal==='function')dialog.showModal();else dialog?.setAttribute('open','');}
  async function saveHomeRecord(event){event.preventDefault();if(!state.active)return;const id=$('homeRecordId').value,type=$('homeRecordType').value,payload={type,eventDate:$('homeRecordDate').value,value:$('homeRecordValue').value,level:$('homeRecordLevel').value,medicationName:$('homeRecordMedication').value.trim(),note:$('homeRecordNote').value.trim()},button=$('homeRecordSave');if(type==='water'&&!payload.value&&!payload.level){status('homeRecordStatus','음수 상태를 선택하거나 측정량을 입력해주세요.','error');return;}button.disabled=true;button.textContent='저장 중…';status('homeRecordStatus');try{await api(`/home/patients/${encodeURIComponent(state.active.patient.id)}/records${id?'/'+encodeURIComponent(id):''}`,{method:id?'PUT':'POST',body:JSON.stringify(payload)});closeHomeRecord();await openPatient(state.active.patient.id);}catch(e){status('homeRecordStatus',e.message,'error');}finally{button.disabled=false;button.textContent='저장';}}
  async function deleteHomeRecord(id){if(!state.active||!id)return;const record=(state.timeline?.events||[]).find(e=>e.id===id);if(!record||!confirm(`“${record.title||'홈 기록'}”을 삭제할까요?`))return;try{await api(`/home/patients/${encodeURIComponent(state.active.patient.id)}/records/${encodeURIComponent(id)}`,{method:'DELETE'});await openPatient(state.active.patient.id);}catch(e){alert(e.message||'홈 기록을 삭제하지 못했습니다.');}}
  async function openPatient(patientId){const context=patientContext(patientId);if(!context)return;state.active=context;state.filter='all';$('patientName').textContent=context.patient.name||'반려동물';$('patientClinicName').textContent=context.connection.clinicName||'연결 병원';$('patientMeta').textContent=[speciesLabel(context.patient.species),context.patient.breed,sexLabel(context.patient.sex)].filter(Boolean).join(' · ');$('patientTimelineBody').hidden=true;$('patientTimelineLoading').hidden=false;$('patientTimelineLoading').innerHTML='<span class="home-spinner" aria-hidden="true"></span><b>건강 기록을 불러오는 중입니다</b>';show('patientView');try{state.timeline=await api(`/home/patients/${encodeURIComponent(patientId)}/timeline?limit=300`,{method:'GET'});renderTimeline();$('patientTimelineLoading').hidden=true;$('patientTimelineBody').hidden=false;}catch(e){$('patientTimelineLoading').innerHTML=`<div class="home-timeline-empty"><b>건강 기록을 불러오지 못했습니다</b><p>${esc(e.message)}</p><button id="patientTimelineRetry" class="home-secondary" type="button">다시 시도</button></div>`;$('patientTimelineRetry')?.addEventListener('click',()=>openPatient(patientId));}}
  async function restore(){if(!state.token){show('loginView');return;}show('loadingView');try{const data=await api('/home/me',{method:'GET'});renderHome(data.home);show('dashboardView');await openPreventiveDeepLink();}catch(e){if(e.status===401){state.token='';localStorage.removeItem(SESSION_KEY);show('loginView');}else showError(e.message);}}
  function showError(message){$('errorMessage').textContent=message||'병원에 새 초대 링크를 요청해주세요.';show('errorView');}
  async function logout(){const token=state.token;state.token='';localStorage.removeItem(SESSION_KEY);try{if(token){state.token=token;await api('/home/logout',{method:'POST'});}}catch{}finally{state.token='';state.home=null;state.timeline=null;state.followups=[];show('loginView');}}
  function onlineStatus(){const offline=!navigator.onLine;$('offlineBar').hidden=!offline;}
  function bindInstall(){window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.installPrompt=e;$('installApp').hidden=false;});$('installApp').addEventListener('click',async()=>{if(!state.installPrompt)return;state.installPrompt.prompt();await state.installPrompt.userChoice;state.installPrompt=null;$('installApp').hidden=true;});window.addEventListener('appinstalled',()=>{$('installApp').hidden=true;state.installPrompt=null;});}
  async function init(){$('inviteForm').addEventListener('submit',acceptInvite);$('loginForm').addEventListener('submit',login);$('logoutButton').addEventListener('click',logout);$('homeHealthConsentSubmit').addEventListener('click',acceptHealthConsent);$('homeFollowupRefresh').addEventListener('click',loadFollowups);$('homePushToggle').addEventListener('click',togglePush);$('homePushTest').addEventListener('click',testPush);$('patientBack').addEventListener('click',()=>show('dashboardView'));$('patientTimelineRefresh').addEventListener('click',()=>state.active&&openPatient(state.active.patient.id));$('homeRecordOpen').addEventListener('click',()=>openHomeRecord());$('homeRecordType').addEventListener('change',()=>{syncHomeRecordFields();$('homeRecordValue').value='';});$('homeRecordForm').addEventListener('submit',saveHomeRecord);$('homeRecordClose').addEventListener('click',closeHomeRecord);$('homeRecordCancel').addEventListener('click',closeHomeRecord);$('homeRecordDialog').addEventListener('cancel',event=>{event.preventDefault();closeHomeRecord();});window.addEventListener('online',onlineStatus);window.addEventListener('offline',onlineStatus);onlineStatus();bindInstall();if('serviceWorker' in navigator)pushRegistration().catch(()=>{});if(state.inviteToken)await loadInvite();else await restore();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
